name: Consul Integration Build
run-name: "Event: Tag ${{ github.event.client_payload.tag }} from ${{ github.event.client_payload.repo }}  #${{ github.run_number }}"

permissions:
  contents: write
  packages: write
  actions: read

on:
  repository_dispatch:
    types: [integration-consul-built]

env:
  EVENT_TAG: ${{ github.event.client_payload.tag }}
  EVENT_BASE_IMAGE: ${{ github.event.client_payload.base_image }}
  EVENT_OWNER: ${{ github.event.client_payload.owner }}
  EVENT_REPO: ${{ github.event.client_payload.repo }}
  BRANCH: "feature/consul-patched"

jobs:
  update-image-reference:
    runs-on: ubuntu-latest
    outputs:
      TARGET_BRANCH: ${{ steps.update_image.outputs.target_branch }}
    steps:
      - name: Check payload
        run: |
          echo "TAG=${{ env.EVENT_TAG }}"
          echo "BASE_IMAGE=${{ env.EVENT_BASE_IMAGE }}"
          echo "OWNER=${{ env.EVENT_OWNER }}"
          echo "REPO_NAME=${{ env.EVENT_REPO }}"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Update image reference
        id: update_image
        run: |
          IMAGE=${{ env.EVENT_BASE_IMAGE }}
          BRANCH=${{ env.BRANCH }}
          echo "target_branch=${BRANCH}" >> "$GITHUB_OUTPUT"

          FILE="charts/helm/consul-service/values.yaml"

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]qubership.com"
          git checkout -B "$BRANCH"

          echo "Updating Consul image to: $IMAGE"
          sed -i "0,/^  image: \".*\"/s|^  image: \".*\"|  image: \"$IMAGE\"|" "$FILE"

          echo "Diff:"
          git diff -- "$FILE"

          if git diff --quiet "$FILE"; then
            echo "No changes detected."
            exit 0
          fi

          git add "$FILE"
          git commit -m "[IBuild] Update Consul with [patched] image to $IMAGE"
          git push origin "$BRANCH" --force
  consul-pipeline:
    needs: update-image-reference
    runs-on: ubuntu-latest
    steps:
      - name: Consul Integration Pipeline
        run: |
          echo "This is a placeholder for the Consul integration pipeline."
          echo "Target branch from previous job: ${{ needs.update-image-reference.outputs.TARGET_BRANCH }}"
    # uses: Netcracker/qubership-test-pipelines/.github/workflows/consul.yaml@d45ea797961a4886faeb675da5d75de90c2bd8c0
    # with:
    #   service_branch: "${{ needs.update-image-reference.outputs.TARGET_BRANCH }}"
    #   versions_file: ".github/versions.yaml"
    #   pipeline_branch: "d45ea797961a4886faeb675da5d75de90c2bd8c0" #this value must match the value after '@' in 'uses'
    # secrets:
    #   AWS_S3_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
    #   AWS_S3_ACCESS_KEY_SECRET: ${{ secrets.AWS_S3_ACCESS_KEY_SECRET }}
